
def options(opt):
    opt.load("projects")
    opt.load_project('rant')
#    opt.load_project('ztl_local')
    opt.load_project('ztl')
#    opt.load_project('pest')


def configure(ctx):
    ctx.load("projects")
    pass
