
# default wscript
# can be modified/deleted if needed

def options(opt):
    # from pudb import set_trace; set_trace()
    pass

def depends(dep):
    dep._recurse_projects()

def configure(cfg):
    pass

def build(bld):
    pass

