
def options(opt):
    opt.load("projects")

    opt.load_project('rant')
    opt.load_project('ztl') #, branch = 'pythonic')
#    opt.load_project('pest')


def configure(ctx):
    ctx.load("projects")
    pass
