#!/bin/bash -e

# File:         executeSymwaf2icTest
# Author:       Kai Husmann <kai.husmann@kip.uni-heidelberg.de> (KHS)
# Changelog:    [2015-04-17 15:02:21]   created/released (KHS)
#               [2015-04-17 15:02:37]   now hiding make (KHS)
# --- chlog insert above ---


# PREREQUISITES
TEST=${1:-"1"}
test -f "waf-light" || { echo "ERR: looks like we're executed in the wrong directory."; exit 1; }
mkdir -p Test
ln -sf ../waf Test/waf


# TEST FUNCTIONS
function test_1 { # DEFAULT
    ./waf setup --project halbe --zones symwaf2ic
}
function test_2 {
   ./waf setup --project halbe --zones symwaf2ic --with-ess
}
function test_reset {
    test -d halbe && { pushd halbe; git checkout -f ess_trafo; echo "fu" >> project.prj; popd; }
   ./waf setup --project halbe --update-branches force --zones symwaf2ic,symwaf2ic_deb,mr
}

function test_super {
    for t in 1 2 reset
    do
        set -o xtrace
        test_$t
        set +o xtrace
        echo -e "\n\n############################################################\n\n"
    done
}

# BUILDING SYMWAF2IC
function build {
    make > Test/make.log 2> Test/make.err
    ERR=$?
    if [ $ERR -ne 0 ]
    then
        cat Test/make.log
        cat Test/make.err
        return 1
    fi
}

build || { echo "ERR: make failed, aborting test!"; exit 1; }


# TESTING
cd Test
rm -rf .waf-*
set -o xtrace
test_$TEST

