#!/bin/bash

git commit -am "wip - publishing test" ||  {
  # TODO compare with head of jenkins_test and push if different otherwise print the following ERROR and exit.
  echo "WARNING: Nothing changed, could not make commit, git add?"
  #exit 1;
}
echo

TEST_TAG="symwaf2ic-test-head"
DATE="$(date +%F\ %R)"

# Using tags
git tag -f -a -m "Testing Symwaf2ic Waf $DATE" "$TEST_TAG"
git push -f origin "tags/$TEST_TAG"

# alternative: using a dedicated branch
#git push -f origin HEAD:symwaf2ic-dev

echo -e "\nNew test published: $DATE."
# usage:
# test -d REPODIR || git clone REPO -b jenkins-test-head REPODIR
# cd REPODIR; git fetch --tags; git reset --hard tags/jenkins-test-head; cd ..
# or, in an already cloned repo, use git checkout -q "tags/jenkins-test-head"

# TODO maybe open up an app window, but don't do this...
#firefox "https://brainscales-r.kip.uni-heidelberg.de:8443/user/khusmann/my-views/view/SymPrj/job/p-khs_sjde-gen-feature/"
