from waflib import Task, TaskGen
top = '.'
out = 'build'
APPNAME = 'TestProject'
VERSION = '1.0'

def options(opt):
	opt.load('xcode6')

def configure(conf):
	
	conf.env.FRAMEWORK_VERSION = '1.0'
	conf.env.ARCHS = 'x86_64'
	conf.env.MACOSX_DEPLOYMENT_TARGET = '10.9'
	conf.env.SDKROOT = 'macosx10.9'

	conf.load('xcode6')

def build(bld):
	
	tg = bld.framework(
		source=bld.path.ant_glob('src/MyLib/*.cpp'),
		includes='include',
		group_files={
			'Include': bld.path.ant_glob('include/MyLib/*.h')
		},

		# export_headers will put the files in the Header
		# buildphase in Xcode - i.e ship them with your .framework
		export_headers=bld.path.ant_glob('include/MyLib/*.h'),
		target='MyLib',
	)

	bld.env.LIB_SDL2 = '/Library/Frameworks/SDL2.framework/SDL2'
	tg2 = bld.app(
		source=bld.path.ant_glob('src/*.cpp|'),
		includes=tg.includes,
		target='MyApp',
		use='MyLib',
		uselib='SDL2',
		cxxflags='-O3',
		framework='Cocoa',
		settings={"Debug": {"CONFIG_NAME": 'Debug'}}
	)

	bld.dylib(
		source=tg.source,
		includes=tg.includes,
		target='MyDynLib',
	)

	bld.exe(
		source=tg.source,
		includes=tg.includes,
		target='MyExe',
	)

	bld.stlib(
		source=tg.source,
		includes=tg.includes,
		target='MyStaticLib',
	)
	