#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.recurse('test0 test1')

	bld(
		features = 'cxx stlib',
		source   = 'gtest_main.cc',
		use      = 'GTEST',
		target   = 'unittestmain')
