#! /usr/bin/env python
# encoding: utf-8

"""
Call 'waf configure display'
"""

def configure(conf):
	pass

from waflib.Build import EnvContext
class fu_class(EnvContext):
	cmd = 'display'

def display(self):
	print(self.env.PREFIX)


