#! /usr/bin/env python

from waflib import Utils

def build(bld):

	if bld.cmd == 'install':
		try:
			bld.exec_command(["update-mime-database", Utils.subst_vars("${DATADIR}/mime", bld.env)])
			bld.exec_command(["update-desktop-database", Utils.subst_vars("${DATADIR}/applications", bld.env)])
		except:
			pass

	bld(
		features  = "intltool_in",
		podir     = "../po",
		style     = "desktop",
		source    = 'kupfer.desktop.in',
		target    = 'kupfer.desktop',
		install_path = "${DATADIR}/applications",
	)

	bld(
		features  = "intltool_in",
		podir     = "../po",
		style     = "xml",
		source    = 'kupfer-mimetypes.xml.in',
		target    = 'kupfer-mimetypes.xml',
		install_path = "${DATADIR}/mime/packages/",
	)


