#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

"""
Note: the #warning will come once when the .h is compiled, it should not not come when the .cpp is compiled when precompiled headers are enabled
"""

#################################################
# example below

VERSION='0.0.2'
APPNAME='pch_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx')
	opt.load('pch boost', tooldir=['../../waflib/extras'])

def configure(conf):
	conf.load('compiler_cxx pch')

	# to include <boost/asio.hpp> to slow down compilation of precompiled headers
	conf.load('boost')
	conf.check_boost('system')

def build(bld):
	# Simple way, when precompiled header is used in a single build task
	bld.program(
		target='test',
		features='pch',
		source='a.cpp b.cpp c.cpp main.cpp',
		headers='a.h b.h c.h',
		use='BOOST')

	# More complex way, where precompiled header is reused by several build tasks
	bld(features='cxx pch',
		name='base-with-pch',
		target='pch-header',
		headers='a.h b.h c.h',
		source='a.cpp',
		use='BOOST')

	bld.program(
		target  = 'test1',
		source  = 'b.cpp c.cpp main.cpp',
		use = 'base-with-pch')
