#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2016
#
# DESTDIR=/tmp/somedir waf install

def configure(conf):
	pass

from waflib import TaskGen, Build
@TaskGen.feature('ruler')
@TaskGen.before('process_rule')
def stuff(self):
	if not self.bld.is_install:
		while self.meths:
			self.meths.pop()
		return

	tg = self.bld.get_tgen_by_name(self.bring_in)
	tg.post() # as a task generator
	assert tg.install_task.outputs
	self.source = tg.install_task.outputs # tg is a task object

def build(bld):
	bld.install_as('${PREFIX}/bin/foo', 'wscript', chmod = 0555)
	bld.symlink_as('${PREFIX}/bin/bar', 'foo')
	tsk = bld.install_files('${PREFIX}/bin', 'wscript', chmod = 0555, name='cheese')
	bld(rule='ls -l ${SRC}', always=True, bring_in='cheese', features='ruler')


