#! /usr/bin/env python

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')
	conf.load('strip', tooldir='.')

def build(bld):
	bld.shlib(features='strip', source='a.c', target='lib1')
	bld.program(features='strip', source='main.c', target='app', use='lib1')

